apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  labels:
    app: laravel
data:
  nginx.conf: |
    events {
    }
    http {
      server {
        listen 80 default_server;
        listen [::]:80 default_server;
        index index.php index.html;
        # Set nginx to serve files from the shared volume!
        root /var/www/html/laravel-app/public;
        server_name _;
        location / {
          try_files $uri $uri/ /index.php$is_args$args;
        }
        location ~ \.php$ {
          include fastcgi_params;
          fastcgi_param REQUEST_METHOD $request_method;
          fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
          fastcgi_pass localhost:9000;
        }
      }
    }  